server:
  port: 8090

spring:
  application:
    name: ms-users
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-realm-dev

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: spring-client-api-rest
